# Generated by Django 4.2.23 on 2025-07-07 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0002_usersolvedproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersolvedproblem',
            name='solved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
