# Generated by Django 4.2.23 on 2025-07-07 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_problems_solved_user_total_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total_score',
        ),
    ]
